name: "Deployment"
# the event that will trigger the action
on:
  push:
    branches:
      - main
  workflow_dispatch:

# what the action will do
jobs:
  publish:
    # the operating system it will run on
    runs-on: ubuntu-latest
    # the list of steps that the action will go through
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Get yarn cache directory path # get yarn cache path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2 # cache yarn
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: "Install Dependencies"
        run: yarn
      - name: "Github Pages Deployment"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      - name: "Set the remote URL"
        run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        if: ${{ github.ref == 'refs/heads/main' }} # only deploy main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}